include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_relative_imports: true
    prefer_single_quotes: true
    require_trailing_commas: true
    unnecessary_lambdas: true
    prefer_expression_function_bodies: true
    lines_longer_than_80_chars: true
    prefer_adjacent_string_concatenation: false
    avoid_function_literals_in_foreach_calls: false
