const String RAISED_HAND_REQUEST = 'RAISED_HAND_REQUEST';
const String RAISED_HAND_ACCEPT = 'RAISED_HAND_ACCEPT';
const String RAISED_HAND_REJECT = 'RAISED_HAND_REJECT';
const String HOST_REQUEST_YOU_BECOME_HOST = 'HOST_REQUEST_YOU_BECOME_HOST';
const String REQUEST_TO_BECOME_HOST_ACCEPTED =
    'REQUEST_TO_BECOME_HOST_ACCEPTED';
const String REQUEST_TO_BECOME_HOST_REJECTED =
    'REQUEST_TO_BECOME_HOST_REJECTED';
const String LEAVE_MIC = 'LEAVE_MIC';
const String HOST_REQUEST_YOU_BECOME_COHOST = 'HOST_REQUEST_YOU_BECOME_COHOST';
const String REQUEST_TO_BECOME_COHOST_ACCEPTED =
    'REQUEST_TO_BECOME_COHOST_ACCEPTED';
const String REQUEST_TO_BECOME_COHOST_REJECTED =
    'REQUEST_TO_BECOME_COHOST_REJECTED';
const String HOST_INVITE_TO_SPEAK = 'HOST_INVITE_TO_SPEAK';
const String INVITE_TO_SPEAK_ACCEPTED = 'INVITE_TO_SPEAK_ACCEPTED';
const String INVITE_TO_SPEAK_REJECTED = 'INVITE_TO_SPEAK_REJECTED';
